services:
  sdk:
    image: openwrt/sdk:aarch64_cortex-a53
    volumes:
      - .:/builder/local-build/luci-app-natmap
      - ./bin:/builder/bin
      - ./build.sh:/builder/build.sh
    command: /builder/build.sh
      